global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'auth-scraper'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/api/auth/metrics'
    scheme: 'http'
